// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGudN87wFLFnSJlAa9z-cE9KyLD2Z18zY',
    appId: '1:769859517248:web:c683ee0e93e93c930598a5',
    messagingSenderId: '769859517248',
    projectId: 'rapid-response-system-df221',
    authDomain: 'rapid-response-system-df221.firebaseapp.com',
    storageBucket: 'rapid-response-system-df221.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFjayKGRwTGa3NK3QLfPOSfXfpvod2eK8',
    appId: '1:769859517248:android:e0af0870c16a036e0598a5',
    messagingSenderId: '769859517248',
    projectId: 'rapid-response-system-df221',
    storageBucket: 'rapid-response-system-df221.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ9O2ORe4K7oX558Gi8wXt3Jkb_ytiTV4',
    appId: '1:769859517248:ios:316f27f213660d930598a5',
    messagingSenderId: '769859517248',
    projectId: 'rapid-response-system-df221',
    storageBucket: 'rapid-response-system-df221.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ9O2ORe4K7oX558Gi8wXt3Jkb_ytiTV4',
    appId: '1:769859517248:ios:316f27f213660d930598a5',
    messagingSenderId: '769859517248',
    projectId: 'rapid-response-system-df221',
    storageBucket: 'rapid-response-system-df221.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGudN87wFLFnSJlAa9z-cE9KyLD2Z18zY',
    appId: '1:769859517248:web:70b33775ca451d130598a5',
    messagingSenderId: '769859517248',
    projectId: 'rapid-response-system-df221',
    authDomain: 'rapid-response-system-df221.firebaseapp.com',
    storageBucket: 'rapid-response-system-df221.firebasestorage.app',
  );
}
